algoritmo "Somador"
// Função : Estrutura de Repetição 2_ex.01
// Autor : Flavio Gomes
// Data : 03/06/2021
// Seção de Declarações 
var
       N, Cont, S: Inteiro
inicio
       S <- 0
       Cont <- 1
       Enquanto (Cont <= 5) faca
                Escreva ("Digite o ", Cont, "o.valor ==> ")
                Leia (N)
                S <- S + N
                Cont <- Cont + 1
       FimEnquanto (C <= Q) faca
       EscrevaL ("A soma de todos os valores digitados e ", S)
fimalgoritmo
