algoritmo "ConteAte10"
// Função : Estrutura de Repetição 1_ex.8
// Autor : Flavio Gomes
// Data : 31/05/2021
// Seção de Declarações 
var
       valor, contador: Inteiro
inicio
       contador <- 0
       Escreva("Quer contar até quanto?")
       Leia(valor)
       Enquanto (contador <= valor) faca
                EscrevaL(contador)
                contador <- contador +1
       FimEnquanto
       EscrevaL("Terminei de contar")
fimalgoritmo
